# Generated by Django 6.0.5 on 2026-05-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('sector_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sector_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dim_sector',
                'managed': False,
            },
        ),
    ]
