# Generated by Django 6.0.5 on 2026-05-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLScore',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('profitability_score', models.FloatField(blank=True, null=True)),
                ('growth_score', models.FloatField(blank=True, null=True)),
                ('leverage_score', models.FloatField(blank=True, null=True)),
                ('cashflow_score', models.FloatField(blank=True, null=True)),
                ('dividend_score', models.FloatField(blank=True, null=True)),
                ('trend_score', models.FloatField(blank=True, null=True)),
                ('health_label', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'fact_ml_scores',
                'managed': False,
            },
        ),
    ]
