# Generated by Django 6.0.5 on 2026-05-10 18:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiclient',
            old_name='api_secret',
            new_name='secret_encrypted',
        ),
        migrations.RemoveField(
            model_name='apiclient',
            name='api_key',
        ),
        migrations.AddField(
            model_name='apiclient',
            name='key_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
