# Generated by Django 6.0.5 on 2026-05-10 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_rename_api_secret_apiclient_secret_encrypted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APINonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.apiclient')),
            ],
            options={
                'unique_together': {('client', 'nonce')},
            },
        ),
    ]
