# Generated by Django 6.0.5 on 2026-05-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_apiusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiclient',
            name='tier',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], default='BASIC', max_length=20),
        ),
    ]
