# Generated by Django 6.0.5 on 2026-05-11 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_apiclient_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooksubscription',
            name='event_type',
            field=models.CharField(choices=[('score_updated', 'Score Updated'), ('anomaly_flagged', 'Anomaly Flagged')], max_length=100),
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('score_updated', 'Score Updated'), ('anomaly_flagged', 'Anomaly Flagged')], max_length=100)),
                ('company_symbol', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('webhook_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='partners.webhooksubscription')),
            ],
        ),
    ]
