# Generated by Django 6.0.5 on 2026-05-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('period_label', models.CharField(max_length=50)),
                ('compounded_sales_growth_pct', models.FloatField(blank=True, null=True)),
                ('compounded_profit_growth_pct', models.FloatField(blank=True, null=True)),
                ('stock_price_cagr_pct', models.FloatField(blank=True, null=True)),
                ('roe_pct', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fact_analysis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfitLoss',
            fields=[
                ('symbol', models.CharField(max_length=20)),
                ('year_id', models.IntegerField(db_column='year_id', primary_key=True, serialize=False)),
                ('sales', models.FloatField(blank=True, null=True)),
                ('net_profit', models.FloatField(blank=True, null=True)),
                ('eps', models.FloatField(blank=True, null=True)),
                ('opm_pct', models.FloatField(blank=True, db_column='opm_pct', null=True)),
            ],
            options={
                'db_table': 'fact_profit_loss',
                'managed': False,
            },
        ),
    ]
